import type { FrameByFrameSlotSymbolConfig } from ".";

export const frameByFrameSlotSymbols: FrameByFrameSlotSymbolConfig[] = [
  {
    id: "letter-a",
    name: "Letter A",
    jsonPath: "/SpineFiles/letter-a/letter-a.json",
    imagePath: "/SpineFiles/letter-a/letter-a.png",
    sourceWidth: 197,
    sourceHeight: 185,
    fps: 30,
  },
  {
    id: "letter-j",
    name: "Letter J",
    jsonPath: "/SpineFiles/letter-j/letter-j.json",
    imagePath: "/SpineFiles/letter-j/letter-j.png",
    sourceWidth: 197,
    sourceHeight: 185,
    fps: 30,
  },
  {
    id: "letter-k",
    name: "Letter K",
    jsonPath: "/SpineFiles/letter-k/letter-k.json",
    imagePath: "/SpineFiles/letter-k/letter-k.png",
    sourceWidth: 197,
    sourceHeight: 185,
    fps: 30,
  },
  {
    id: "letter-q",
    name: "Letter Q",
    jsonPath: "/SpineFiles/letter-q/letter-q.json",
    imagePath: "/SpineFiles/letter-q/letter-q.png",
    sourceWidth: 197,
    sourceHeight: 185,
    fps: 30,
  },
  {
    id: "number-10",
    name: "Number 10",
    jsonPath: "/SpineFiles/number-10/number-10.json",
    imagePath: "/SpineFiles/number-10/number-10.png",
    sourceWidth: 180,
    sourceHeight: 169,
    fps: 30,
  },
  {
    id: "cell",
    name: "Cell",
    jsonPath: "/SpineFiles/Cell/cell.json",
    imagePath: "/SpineFiles/Cell/cell.png",
    sourceWidth: 188,
    sourceHeight: 124,
    fps: 30,
  },
  {
    id: "dynamit",
    name: "Dynamit",
    jsonPath: "/SpineFiles/Dynamit/dynamit.json",
    imagePath: "/SpineFiles/Dynamit/dynamit.png",
    sourceWidth: 279,
    sourceHeight: 281,
    fps: 30,
  },
  {
    id: "handcuffs",
    name: "Handcuffs",
    jsonPath: "/SpineFiles/Handcuffs/handcuffs.json",
    imagePath: "/SpineFiles/Handcuffs/handcuffs.png",
    sourceWidth: 182,
    sourceHeight: 167,
    fps: 30,
  },
];
